# Vincent Romulus S. Sarmiento | 2ECE-D


## A. Reproducible Normalization Problem

In [9]:
import numpy as np

In [10]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
M = np.mean(X)
S = np.std(X)
X_normalized = (X - M) / S
M_normalized = np.mean(X_normalized)
S_normalized = np.std(X_normalized)
M_str = str(M_normalized)
S_str = str(S_normalized)

In [11]:
print("Array X: \n", X)

Array X: 
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]


In [12]:
print("Array X_normalized: \n", X_normalized)

Array X_normalized: 
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]


In [13]:
print("Mean: " + M_str)
print("Standard Deviation: " + S_str)

Mean: 0.0
Standard Deviation: 0.9999999999999999


In [14]:
np.save('X_normalized.npy', X_normalized)

## B. Cubes Divisible by 4 Problem

In [15]:
C = (np.arange(1, 101) ** 3).reshape(10, 10)
div_by_4 = C[C % 4 == 0]

In [16]:
print("Shape of C:", C.shape)

Shape of C: (10, 10)


In [17]:
print("Array div_by_4: \n", div_by_4)

Array div_by_4: 
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [18]:
div_by_4_str = str(div_by_4.size)
print("Size of div_by_4:", div_by_4_str)

Size of div_by_4: 50


In [19]:
np.save('div_by_4.npy', div_by_4)

## C. Above-mean Squares Problem

In [20]:
import numpy as np

In [21]:
S = (np.arange(1, 37) ** 2).reshape(6, 6)
S_mean = np.mean(S)
above_mean = S[S > S_mean]
above_mean_str = str(above_mean)

In [22]:
print("Array S: \n", S)

Array S: 
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [23]:
print("Mean of S:", S_mean)

Mean of S: 450.1666666666667


In [24]:
print("Array above_mean: \n", above_mean)

Array above_mean: 
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [25]:
above_mean_str = str(above_mean.size)
print("Size of above_mean:", above_mean_str)

Size of above_mean: 15


In [26]:
np.save('above_mean.npy', above_mean)